projects:
  apimvisual:
    schemaPath: amplify/backend/api/apimvisual/build/schema.graphql
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
